# Generated by Django 5.0.4 on 2024-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "医生"), (2, "普通用户"), (3, "管理员")],
                        default=2,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "identity_num",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="证件号",
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="用户密码")),
            ],
        ),
    ]
