version: '3'
networks:
  custom_app_net:
    name: app_net
    external: true
services:
  database: 
    image: mysql
    container_name: mysql-test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '@15755083308Ab'
      MYSQL_DATABASE: 'seproject'
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - custom_app_net
