version: '3'
services:
  database: 
    image: mysql
    container_name: mysql5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '@15755083308Ab'
      MYSQL_DATABASE: 'seproject'
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
  web:
    image: back-app
    container_name: back-app-1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
