# Generated by Django 5.0.4 on 2024-08-20 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.IntegerField(verbose_name="医生编号")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="值班日期"
                    ),
                ),
                (
                    "time",
                    models.SmallIntegerField(
                        choices=[(1, "上午"), (2, "下午"), (3, "晚上")],
                        default=1,
                        verbose_name="值班时间",
                    ),
                ),
                ("state", models.IntegerField(verbose_name="预约状态")),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_id", models.IntegerField(default=1, verbose_name="排队号")),
                ("patient", models.IntegerField(verbose_name="患者证件号")),
                ("doctor", models.IntegerField(verbose_name="医生编号")),
                ("time", models.DateTimeField(verbose_name="就诊时间")),
                ("advice", models.CharField(max_length=256, verbose_name="诊断结果")),
                ("medicine", models.TextField(verbose_name="开具药物")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="处方总价"
                    ),
                ),
            ],
        ),
    ]
