version: '3'
services:
  user_service:
    build:
      context: user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5004:5004" # 映射端口

  patient_service:
    build:
      context: patient_service
      dockerfile: Dockerfile
    container_name: patient_service
    ports:
      - "5001:5001" # 映射端口

  doctor_service:
    build:
      context: doctor_service
      dockerfile: Dockerfile
    container_name: doctor_service
    ports:
      - "5002:5002" # 映射端口

  administrator_service:
    build:
      context: administrator_service
      dockerfile: Dockerfile
    container_name: administrator_service
    ports:
      - "5003:5003" # 映射端口


  nginx:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - user_service
      - patient_service
      - doctor_service
      - administrator_service