version: '3'
services:
  # database: 
  #   image: mysql
  #   container_name: mysql5.7
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '@15755083308Ab'
  #     MYSQL_DATABASE: 'seproject'
  #   command: 
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_unicode_ci
  user_service:
    build:
      context: user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5004:5004" # 映射端口
    # depends_on:
    #   - database
  patient_service:
    build:
      context: patient_service
      dockerfile: Dockerfile
    container_name: patient_service
    ports:
      - "5001:5001" # 映射端口
    # depends_on:
    #   - database
  doctor_service:
    build:
      context: doctor_service
      dockerfile: Dockerfile
    container_name: doctor_service
    ports:
      - "5002:5002" # 映射端口
    # depends_on:
    #   - database
  administrator_service:
    build:
      context: administrator_service
      dockerfile: Dockerfile
    container_name: administrator_service
    ports:
      - "5003:5003" # 映射端口
    # depends_on:
    #   - database

  nginx:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - user_service
      - patient_service
      - doctor_service
      - administrator_service