version: '3'
services:
  # database:
  #   image: mysql
  #   container_name: mysql5.7
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '@15755083308Ab'
  #     MYSQL_DATABASE: 'seproject'
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    image: my-django-app
    container_name: django-app
    ports:
      - "5001:5001"
    # command: /usr/sbin/nginx -s reload 
    # command: uwsgi /app/uwsgi.ini

    # depends_on:
    #   - database

  nginx:
    image: vue-hello
    container_name: nginx
    ports:
      - "80:80"
    restart: always # always表容器运行发生错误时一直重启
    depends_on:
      - web
