# Generated by Django 5.0.4 on 2024-05-10 13:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="医生姓名")),
                ("title", models.CharField(max_length=50, verbose_name="医生职称")),
                ("section", models.CharField(max_length=20, verbose_name="医生科室")),
                (
                    "research",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="研究方向"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="药物名字")),
                (
                    "medicine_type",
                    models.SmallIntegerField(
                        choices=[(1, "中药"), (2, "中成药"), (3, "西药")],
                        verbose_name="药物种类",
                    ),
                ),
                ("symptom", models.CharField(max_length=200, verbose_name="适应症状")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="药物价格"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="患者姓名")),
                (
                    "health_insurance",
                    models.SmallIntegerField(
                        choices=[(1, "医保"), (2, "非医保")],
                        default=1,
                        verbose_name="医保情况",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="患者性别"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        default=datetime.date.today, verbose_name="患者生日"
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(
                        default="", max_length=15, verbose_name="患者电话"
                    ),
                ),
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[
                            (1, "身份证"),
                            (2, "医保卡"),
                            (3, "诊疗卡"),
                            (4, "护照"),
                            (5, "军官证"),
                            (6, "港澳通行证"),
                        ],
                        default=1,
                        verbose_name="身份证明",
                    ),
                ),
                (
                    "identity_num",
                    models.CharField(default="", max_length=64, verbose_name="证件号"),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=128, verbose_name="患者住址"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "account",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户账号",
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="用户密码")),
                (
                    "user_type",
                    models.SmallIntegerField(
                        choices=[(1, "患者"), (2, "医生"), (3, "管理员")],
                        verbose_name="用户类型",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnDuty",
            fields=[
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app01.doctors",
                        verbose_name="医生编号",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="值班日期"
                    ),
                ),
                (
                    "time",
                    models.SmallIntegerField(
                        choices=[(1, "上午"), (2, "下午"), (3, "晚上")],
                        default=1,
                        verbose_name="值班时间",
                    ),
                ),
                ("state", models.IntegerField(verbose_name="预约状态")),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200, verbose_name="通知内容")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.patients",
                        verbose_name="患者编号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="挂号时间")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.doctors",
                        verbose_name="医生编号",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.patients",
                        verbose_name="患者编号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="就诊时间")),
                ("medicine", models.CharField(max_length=200, verbose_name="处方内容")),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(1, "已缴费"), (2, "待缴费")], verbose_name="处方状态"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.doctors",
                        verbose_name="医生编号",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.patients",
                        verbose_name="患者编号",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patients",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.users",
                verbose_name="患者账号",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.users",
                verbose_name="医生账号",
            ),
        ),
    ]
