# Generated by Django 5.0.4 on 2024-05-10 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="time",
        ),
        migrations.AddField(
            model_name="treatment",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="就诊日期"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="queue_id",
            field=models.IntegerField(default=1, verbose_name="排队号"),
        ),
    ]
