# Generated by Django 5.0.4 on 2024-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor/", verbose_name="医生头像"
            ),
        ),
    ]
