# Generated by Django 5.0.4 on 2024-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="avatar_name",
            field=models.CharField(
                default="img", max_length=128, verbose_name="图片名字"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="photo_name",
            field=models.CharField(
                default="img", max_length=128, verbose_name="图片名字"
            ),
        ),
    ]
