# Generated by Django 5.0.4 on 2024-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_doctors_avatar_name_medicine_photo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="药物图片"
            ),
        ),
    ]
