# Generated by Django 5.0.4 on 2024-05-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_doctors_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onduty",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app01.doctors",
                verbose_name="医生编号",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.doctors",
                verbose_name="医生编号",
            ),
        ),
    ]
