# Generated by Django 5.0.4 on 2024-05-11 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_remove_treatment_time_treatment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onduty",
            name="date",
            field=models.DateField(
                default=datetime.date(2024, 5, 11), verbose_name="值班日期"
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="birthday",
            field=models.DateField(
                default=datetime.date(2024, 5, 11), verbose_name="患者生日"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="date",
            field=models.DateField(
                default=datetime.date(2024, 5, 11), verbose_name="就诊日期"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="medicine",
            field=models.TextField(max_length=1024, verbose_name="处方内容"),
        ),
    ]
