# Generated by Django 5.0.4 on 2024-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_onduty_doctor_alter_register_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="medicine/", verbose_name="药物图片"
            ),
        ),
    ]
