# Generated by Django 5.0.4 on 2024-05-11 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_onduty_date_alter_patients_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onduty",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="值班日期"
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="birthday",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="患者生日"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="就诊日期"
            ),
        ),
    ]
