# Generated by Django 5.0.4 on 2024-05-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_medicine_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="photo",
        ),
    ]
