# Generated by Django 5.0.4 on 2024-05-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_medicine_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="state",
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "挂号"), (2, "处方"), (3, "检查")],
                        verbose_name="账单类型",
                    ),
                ),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(1, "已缴费"), (2, "待缴费")], verbose_name="账单状态"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="账单金额"
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.register",
                        verbose_name="挂号编号",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.treatment",
                        verbose_name="处方编号",
                    ),
                ),
            ],
        ),
    ]
