# Generated by Django 5.0.4 on 2024-05-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_remove_treatment_state_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.patients",
                verbose_name="患者证件号",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="state",
            field=models.BooleanField(verbose_name="账单状态"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="type",
            field=models.SmallIntegerField(
                choices=[(1, "挂号"), (2, "处方")], verbose_name="账单类型"
            ),
        ),
    ]
