# Generated by Django 5.0.4 on 2024-05-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_bill_patient_alter_bill_state_alter_bill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.register",
                verbose_name="挂号编号",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.treatment",
                verbose_name="处方编号",
            ),
        ),
    ]
