# Generated by Django 5.0.4 on 2024-08-20 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[
                            (1, "身份证"),
                            (2, "医保卡"),
                            (3, "诊疗卡"),
                            (4, "护照"),
                            (5, "军官证"),
                            (6, "港澳通行证"),
                        ],
                        default=1,
                        verbose_name="身份证明",
                    ),
                ),
                (
                    "identity_num",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="证件号",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="患者姓名")),
                (
                    "health_insurance",
                    models.SmallIntegerField(
                        choices=[(1, "医保"), (2, "非医保")],
                        default=1,
                        verbose_name="医保情况",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="患者性别"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="患者生日"
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(
                        default="", max_length=15, verbose_name="患者电话"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=128, verbose_name="患者住址"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_id", models.IntegerField(default=1, verbose_name="排队号")),
                ("doctor", models.IntegerField(verbose_name="医生编号")),
                ("time", models.DateTimeField(verbose_name="挂号时间")),
                ("position", models.CharField(max_length=128, verbose_name="门诊位置")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_registers",
                        to="patient.patients",
                        verbose_name="患者证件号",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_registers",
                        to="patient.patients",
                        verbose_name="挂号者证件号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.IntegerField(verbose_name="医生编号")),
                (
                    "msg_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "预约成功"),
                            (2, "取消预约"),
                            (3, "处方缴费提醒"),
                            (4, "处方缴费成功"),
                        ],
                        verbose_name="消息类型",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="通知时间")),
                (
                    "treatment",
                    models.IntegerField(blank=True, null=True, verbose_name="处方编号"),
                ),
                ("isRead", models.BooleanField(default=False, verbose_name="已读未读")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notices",
                        to="patient.patients",
                        verbose_name="患者证件号",
                    ),
                ),
                (
                    "registerMan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_notices",
                        to="patient.patients",
                        verbose_name="挂号者证件号",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.register",
                        verbose_name="挂号编号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "挂号"), (2, "处方")], verbose_name="账单类型"
                    ),
                ),
                ("state", models.BooleanField(verbose_name="账单状态")),
                (
                    "treatment",
                    models.IntegerField(blank=True, null=True, verbose_name="处方编号"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="账单金额"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patients",
                        verbose_name="患者证件号",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.register",
                        verbose_name="挂号编号",
                    ),
                ),
            ],
        ),
    ]
