name: Build and Deploy

on:
  push:
    branches: ["microservice"]

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node.js Dependencies
        run: |
          cd 猫猫就诊/Project/frontend
          npm install

      - name: Build Frontend
        run: |
          cd 猫猫就诊/Project/frontend
          npm run build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install back-end dependencies
        working-directory: ./猫猫就诊/Project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit Test
        run: |
          cd 猫猫就诊/Project
          pip install djangorestframework
          pip install Pillow
          python delete_defaultdb.py
          python manage.py test app01

  build-on-windows:
    runs-on: windows-latest
    needs: UnitTest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build frontend on Windows
        run: npm run build
        working-directory: ./猫猫就诊/Project/frontend

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./猫猫就诊/Project/frontend/dist # 前端构建产物

  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    needs: build-on-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ./猫猫就诊/Project/frontend/dist

      #后端产物没有下载了
      - name: ls content
        run: ls

      - name: Deploy to server
        run: bash ./猫猫就诊/Project/deploy.sh
