name: deploy

on:
  push:
    branches: [ "zqstmp" ]
  pull_request:
    branches: [ "zqstmp" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install front-end dependencies
        working-directory: ./猫猫就诊/Project/frontend
        run: npm install

      - name: Build front-end
        working-directory: ./猫猫就诊/Project/frontend
        run: npm run build

      # 后端设置
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install back-end dependencies
        working-directory: ./猫猫就诊/Project/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to server
        run: bash ./deploy.sh