name: Django CI

on:
  push:
    branches: [ "zqstmp" ]
  pull_request:
    branches: [ "zqstmp" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install Node.js Dependencies
      run: |
        cd 猫猫就诊/Project/frontend
        npm install
    - name: Build Frontend
      run: |
        cd 猫猫就诊/Project/frontend
        npm run build


