name: frontend CI

on:
  push:
    branches: [ "zqstmp" ]
  pull_request:
    branches: [ "zqstmp" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install Node.js Dependencies
      run: |
        cd 猫猫就诊/Project/frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd 猫猫就诊/Project/frontend
        npm run build
        
    - name: Unit Test
      run: |
        cd 猫猫就诊/Project
        python .\manage.py test app01

